import React from "react";

// Technology icon mapping
export const technologyIcons: Record<string, string> = {
    react: "SiReact",
    javascript: "SiJavascript",
    js: "SiJavascript",
    typescript: "SiTypescript",
    ts: "SiTypescript",
    html: "SiHtml5",
    css: "SiCss3",
    tailwind: "SiTailwindcss",
    bootstrap: "SiBootstrap",
    node: "SiNodedotjs",
    express: "SiExpress",
    next: "SiNextdotjs",
    vue: "SiVuedotjs",
    angular: "SiAngular",
    three: "SiThreedotjs",
    framer: "SiFramer",
    python: "SiPython",
    mongodb: "SiMongodb",
    postgresql: "SiPostgresql",
    postgres: "SiPostgresql",
    mysql: "SiMysql",
    firebase: "SiFirebase",
    git: "SiGit",
    docker: "SiDocker",
    vite: "SiVite",
    svelte: "SiSvelte",
    graphql: "SiGraphql",
    redux: "SiRedux",
    flutter: "SiFlutter",
    swift: "SiSwift",
    kotlin: "SiKotlin",
    android: "SiAndroid",
    ios: "SiApple",
    unity: "SiUnity",
    arkit: "SiApple",
    arcore: "SiGoogle",
    "c#": "SiCsharp",
    csharp: "SiCsharp",
    d3: "SiD3Dotjs",
    "d3.js": "SiD3Dotjs",
    webgl: "SiWebgl",
    gsap: "SiGreensock",
    canvas: "SiJavascript",
};

// Project data categorized by type
export const webProjects = [
    {
        id: 1,
        title: "QuickStay – Cabin Booking System",
        subtitle:
            "A complete system for managing cabin reservations and guest interactions",
        description:
            "A fully functional booking management platform with real-time cabin availability and guest management.",
        imageUrl: "/assets/WebProjects/quickstay/image1.webp",
        carouselImages: [
            "/assets/WebProjects/quickstay/image1.webp",
            "/assets/WebProjects/quickstay/image2.webp",
            "/assets/WebProjects/quickstay/image3.webp",
            "/assets/WebProjects/quickstay/image4.webp",
        ],
        technologies: ["Next.js", "Supabase", "HTML", "JS", "Tailwind CSS"],
        keyFeatures: [
            "Cabin management with pricing, discounts, and availability tracking",
            "Guest management with secure data storage and updates",
            "Booking system with real-time date conflict handling",
            "Automated keep-alive mechanism to prevent database inactivity",
            "API endpoints for cabin, guest, and booking management",
            "Fully responsive frontend with Josefin Sans typography",
        ],
        demoUrl: "https://quickstay-one.vercel.app/",
        githubUrl: "https://github.com/waqiur/quickstay",
        category: "Full-Stack Development",
    },
    {
        id: 2,
        title: "Natours – Tour Booking System",
        subtitle: "Full-stack Node.js application for seamless tour management",
        description:
            "A feature-rich tour booking platform with secure authentication, real-time bookings, and robust API integrations. Built for scalability, security, and performance.",
        imageUrl: "/assets/WebProjects/natours-server/image1.webp",
        carouselImages: [
            "/assets/WebProjects/natours-server/image1.webp",
            "/assets/WebProjects/natours-server/image2.webp",
            "/assets/WebProjects/natours-server/image3.webp",
            "/assets/WebProjects/natours-server/image4.webp",
        ],
        technologies: [
            "Node.js",
            "Express",
            "MongoDB",
            "Mongoose",
            "HTML",
            "CSS",
            "JS",
            "JWT",
            "Stripe",
            "Pug",
            "Helmet",
        ],
        keyFeatures: [
            "JWT-based authentication with role-based access control",
            "Comprehensive tour management with CRUD, filtering, and sorting",
            "Secure Stripe payment integration for seamless bookings",
            "User management with profile updates and password resets",
            "Optimized performance with caching, compression, and security",
            "MongoDB with Mongoose for efficient data handling",
        ],
        demoUrl: "https://natours-server.vercel.app/",
        githubUrl: "https://github.com/waqiur/natours-server",
        category: "Full-Stack Development",
    },
    {
        id: 3,
        title: "EzyMath",
        subtitle:
            "Comprehensive platform offering calculators and learning tools for mathematics",
        description:
            "A responsive educational platform that provides detailed resources, interactive calculators, and formula renderings using KaTeX for various mathematical topics including calculus, trigonometry, statistics, and more.",
        imageUrl: "/assets/WebProjects/ezymath/image1.webp",
        carouselImages: [
            "/assets/WebProjects/ezymath/image1.webp",
            "/assets/WebProjects/ezymath/image2.webp",
            "/assets/WebProjects/ezymath/image3.webp",
            "/assets/WebProjects/ezymath/image4.webp",
        ],
        technologies: ["HTML5", "CSS3", "JavaScript", "KaTeX"],
        keyFeatures: [
            "Covers topics like calculus, statistics, trigonometry, conic sections, and more",
            "Interactive calculators for solving complex math problems easily",
            "Math formula rendering using KaTeX for clean and accessible presentation",
            "Fully responsive design and user-friendly navigation system",
            "Includes testimonials, subscription features, and social media integration",
            "Performance-optimized with WebP images, script deferring, and CDN usage",
        ],
        demoUrl: "https://ezymath-91z02n0vf-waqiurs-projects.vercel.app/",
        githubUrl: "https://github.com/waqiur/ezymath",
        category: "Frontend Development",
    },
    {
        id: 4,
        title: "usePopcorn",
        subtitle:
            "Movie search, rating, and watchlist tracker with OMDB integration",
        description:
            "A React-based application that allows users to search for movies using the OMDB API, rate them with a custom star component, and manage a watchlist with viewing statistics and localStorage support.",
        imageUrl: "/assets/WebProjects/usePopcorn/image1.webp",
        carouselImages: [
            "/assets/WebProjects/usePopcorn/image1.webp",
            "/assets/WebProjects/usePopcorn/image2.webp",
            "/assets/WebProjects/usePopcorn/image3.webp",
            "/assets/WebProjects/usePopcorn/image4.webp",
        ],
        technologies: ["React", "OMDB API", "HTML", "CSS", "JS"],
        keyFeatures: [
            "Movie search with real-time results from OMDB API",
            "Detailed movie view with metadata and plot",
            "Custom star rating system with user rating storage",
            "Watchlist management with viewing stats",
            "Persistent state with localStorage and custom hooks",
            "Responsive design and keyboard shortcuts for quick actions",
        ],
        demoUrl: "https://usepopcorn-iota.vercel.app/",
        githubUrl: "https://github.com/waqiur/usePopcorn",
        category: "Frontend Development",
    },
    {
        id: 5,
        title: "Node Farm",
        subtitle: "Dynamic product catalog with a custom template engine",
        description:
            "A lightweight web application for showcasing farm products with dynamic content rendering, a custom routing system, and efficient data management.",
        imageUrl: "/assets/WebProjects/node-farm/image1.webp",
        carouselImages: [
            "/assets/WebProjects/node-farm/image1.webp",
            "/assets/WebProjects/node-farm/image2.webp",
            "/assets/WebProjects/node-farm/image3.webp",
        ],
        technologies: ["Node.js", "ES Modules", "HTML", "CSS", "JS"],
        keyFeatures: [
            "Custom routing system for dynamic product pages",
            "Reusable HTML templates for product listings and details",
            "Lightweight template engine for dynamic content replacement",
            "Efficient data management with structured JSON storage",
            "Minimalistic Node.js server with optimized request handling",
        ],
        demoUrl: "https://node-farm-nu.vercel.app/",
        githubUrl: "https://github.com/waqiur/node-farm",
        category: "Web Development",
    },
    {
        id: 6,
        title: "Pizza House",
        subtitle:
            "A fully functional pizza ordering web application built with React, Vite, and TailwindCSS",
        description:
            "Pizza House is a React-based web app that allows users to browse a menu, add pizzas to their cart, manage orders, and track deliveries. It features user authentication, real-time order updates, and geolocation-based address autofill.",
        imageUrl: "/assets/WebProjects/pizza-house/image1.webp",
        carouselImages: [
            "/assets/WebProjects/pizza-house/image1.webp",
            "/assets/WebProjects/pizza-house/image2.webp",
            "/assets/WebProjects/pizza-house/image3.webp",
            "/assets/WebProjects/pizza-house/image4.webp",
        ],
        technologies: [
            "React",
            "Redux",
            "React Router",
            "HTML",
            "Tailwind CSS",
            "JS",
        ],
        keyFeatures: [
            "Dynamic menu with real-time availability and pricing",
            "Comprehensive cart management with quantity updates and removal",
            "Geolocation-based address autofill for seamless ordering",
            "Order tracking with live status updates and estimated delivery time",
            "Priority order feature for faster delivery",
            "Responsive UI with TailwindCSS for a seamless experience",
        ],
        demoUrl: "https://pizza-house-alpha.vercel.app/",
        githubUrl: "https://github.com/Waqiur/pizza-house",
        category: "Full-Stack Development",
    },
    {
        id: 7,
        title: "React Quiz",
        subtitle:
            "An interactive quiz application with dynamic questions and real-time feedback",
        description:
            "A React-based quiz platform that fetches questions from an API, tracks user progress, and provides real-time feedback with score analysis and high score tracking.",
        imageUrl: "/assets/WebProjects/react-quiz/image1.webp",
        carouselImages: [
            "/assets/WebProjects/react-quiz/image1.webp",
            "/assets/WebProjects/react-quiz/image2.webp",
            "/assets/WebProjects/react-quiz/image3.webp",
            "/assets/WebProjects/react-quiz/image4.webp",
        ],
        technologies: ["React", "HTML", "CSS", "JS", "API"],
        keyFeatures: [
            "Dynamic question fetching from environment-specific API endpoints",
            "Real-time timer with countdown for each question",
            "Answer feedback with color-coded highlights for correct/incorrect options",
            "High score tracking and emoji-based finish screen feedback",
            "Responsive design with clean and user-friendly UI",
            "Restart functionality to retake the quiz anytime",
        ],
        demoUrl: "https://react-quiz-six-tau.vercel.app/",
        githubUrl: "https://github.com/Waqiur/react-quiz",
        category: "Frontend Development",
    },
    {
        id: 8,
        title: "The Atomic Blog",
        subtitle:
            "Efficient post creation, archiving, and search system with dark mode and performance testing",
        description:
            "A high-performance React app to manage, search, and archive posts with support for dark mode and responsive layout. Utilizes Context API for scalable state management.",
        imageUrl: "/assets/WebProjects/the-atomic-blog/image1.webp",
        carouselImages: [
            "/assets/WebProjects/the-atomic-blog/image1.webp",
            "/assets/WebProjects/the-atomic-blog/image2.webp",
        ],
        technologies: ["React", "Context API", "HTML", "CSS", "JS"],
        keyFeatures: [
            "Create and archive up to 10,000 posts with efficient state handling",
            "Real-time search with title and body filtering",
            "Fake dark mode toggle using CSS filters and persistent state",
            "Centralized state management via Context and custom hooks",
            "Responsive and grid-based post layout",
            "Performance testing support with Test component",
        ],
        demoUrl: "https://the-atomic-blog-ten.vercel.app/",
        githubUrl: "https://github.com/Waqiur/the-atomic-blog",
        category: "Frontend Development",
    },
    {
        id: 9,
        title: "Travel List",
        subtitle:
            "Interactive item packing list with progress tracking and sorting",
        description:
            "A React-based application to manage a travel packing list. Features include adding, sorting, and tracking packed items with fun visual feedback and responsive UI.",
        imageUrl: "/assets/WebProjects/travel-lists/image1.webp",
        carouselImages: [
            "/assets/WebProjects/travel-lists/image1.webp",
            "/assets/WebProjects/travel-lists/image2.webp",
        ],
        technologies: ["React", "HTML", "CSS", "JS"],
        keyFeatures: [
            "Add, delete, and toggle items as packed or unpacked",
            "Sort items by input order, name, or packed status",
            "Packing progress tracker with percentage and messages",
            "Custom quantity selector and emoji-based UI",
            "Responsive design using custom grid-based CSS",
            "Built with modern React practices using hooks and props",
        ],
        demoUrl: "https://travel-lists-opal.vercel.app/",
        githubUrl: "https://github.com/Waqiur/travel-lists",
        category: "Frontend Development",
    },
    {
        id: 10,
        title: "Workout Timer ",
        subtitle:
            "Customizable timer-based workout with dynamic settings and sound feedback",
        description:
            "A React app that helps users create dynamic workout sessions based on time of day, exercise type, and personalized timer settings with real-time audio feedback and responsive design.",
        imageUrl: "/assets/WebProjects/workout-timer/image1.webp",
        carouselImages: [
            "/assets/WebProjects/workout-timer/image1.webp",
            "/assets/WebProjects/workout-timer/image2.webp",
        ],
        technologies: ["React", "HTML", "CSS", "JS", "Audio API"],
        keyFeatures: [
            "Custom workout types based on time of day (AM/PM)",
            "Adjustable timer controls for sets, exercise time, and breaks",
            "Sound effects and audio feedback for user interaction",
            "Real-time display with AM/PM and countdown in MM:SS",
            "Responsive gradient UI with mobile-friendly layout",
            "Optimized with React hooks and memoization",
        ],
        demoUrl: "https://workout-timer-dh1cjqhep-waqiurs-projects.vercel.app/",
        githubUrl: "https://github.com/waqiur/workout-timer",
        category: "Frontend Development",
    },
    {
        id: 11,
        title: "WorldWise Travel App",
        subtitle:
            "Track your world travels with an interactive map and city management",
        description:
            "A full-featured travel tracker built in React with map integration, city management, and authentication. Plan, log, and revisit your travel history with an intuitive UI.",
        imageUrl: "/assets/WebProjects/worldwise/image1.webp",
        carouselImages: [
            "/assets/WebProjects/worldwise/image1.webp",
            "/assets/WebProjects/worldwise/image2.webp",
            "/assets/WebProjects/worldwise/image3.webp",
        ],
        technologies: [
            "React",
            "React Router",
            "Leaflet",
            "HTML",
            "CSS Modules",
            "JS",
        ],
        keyFeatures: [
            "Authentication system with protected routes and user profile",
            "City management: add, delete, and view city visit history",
            "Interactive map using Leaflet with click-to-add functionality",
            "Routing and navigation with nested and protected routes",
            "Responsive design and loading/error handling with Spinner",
            "Mock backend with JSON Server and lazy-loaded components",
        ],
        demoUrl: "https://worldwise-cu3wktdam-waqiurs-projects.vercel.app/",
        githubUrl: "https://github.com/waqiur/worldwise",
        category: "Full Stack Development",
    },
    {
        id: 12,
        title: "Responsive Modern Website",
        subtitle: "Fully responsive website using modern CSS techniques",
        description:
            "A sleek and responsive multi-section landing page designed with modern CSS features, accessibility in mind, and performance optimizations for fast loading and great user experience across all devices.",
        imageUrl: "/assets/WebProjects/omnifood/image1.webp",
        carouselImages: [
            "/assets/WebProjects/omnifood/image1.webp",
            "/assets/WebProjects/omnifood/image2.webp",
            "/assets/WebProjects/omnifood/image3.webp",
            "/assets/WebProjects/omnifood/image4.webp",
        ],
        technologies: ["HTML5", "CSS3", "CSS Grid", "JS"],
        keyFeatures: [
            "Fluid grid system with media queries for all screen sizes",
            "Sticky navigation with mobile hamburger menu and smooth scrolling",
            "Beautiful components: hero section, testimonials, pricing tables, and more",
            "Consistent visual design with custom properties and rem-based typography",
            "Performance optimized with responsive images and minimal JS usage",
            "Accessible with semantic HTML, ARIA labels, and proper focus states",
        ],
        demoUrl: "https://omnifood-ashen.vercel.app/",
        githubUrl: "https://github.com/waqiur/omnifood",
        category: "Frontend Development",
    },
];

export const appProjects = [
    {
        id: 1,
        title: "Neo AI App",
        subtitle:
            "A versatile AI-powered application offering multiple intelligent features",
        description:
            "Neo AI App integrates advanced AI functionalities, providing users with tools like chatbots, code generation, image creation, language translation, and transcription services.",
        imageUrl: "/assets/AppProjects/neo-ai-app/image9.webp",
        carouselImages: [
            "/assets/AppProjects/neo-ai-app/image1.webp",
            "/assets/AppProjects/neo-ai-app/image2.webp",
            "/assets/AppProjects/neo-ai-app/image3.webp",
            "/assets/AppProjects/neo-ai-app/image4.webp",
            "/assets/AppProjects/neo-ai-app/image5.webp",
            "/assets/AppProjects/neo-ai-app/image6.webp",
            "/assets/AppProjects/neo-ai-app/image7.webp",
            "/assets/AppProjects/neo-ai-app/image8.webp",
        ],
        technologies: [
            "Flutter",
            "Dart",
            "Firebase",
            "OpenAI API",
            "Stripe API",
        ],
        keyFeatures: [
            "Chatbot utilizing GPT-3.5 for interactive conversations",
            "Code generation capabilities powered by OpenAI",
            "Image creation using DALL-E Model API",
            "Language translation services",
            "Transcription services leveraging Whisper Model for efficient processing",
            "Google login integration via Firebase Authentication",
            "Secure data storage with Firebase Cloud Firestore",
            "Seamless in-app payments through Stripe API",
        ],
        githubUrl: "https://github.com/Waqiur/Neo_AI_App",
        category: "Mobile Application Development",
    },
    {
        id: 2,
        title: "GadgetHive",
        subtitle: "A comprehensive electronics e-commerce catalog application",
        description:
            "GadgetHive is a full-featured mobile app showcasing a curated catalog of electronic gadgets like smartphones, laptops, tablets, and audio devices. Users can explore, compare, and purchase products through a seamless UI and secure payment system.",
        imageUrl: "/assets/AppProjects/gadgethive/image1.webp",
        carouselImages: [
            "/assets/AppProjects/gadgethive/image2.webp",
            "/assets/AppProjects/gadgethive/image3.webp",
            "/assets/AppProjects/gadgethive/image3.webp",
            "/assets/AppProjects/gadgethive/image5.webp",
        ],
        technologies: ["Flutter", "Dart", "Firebase", "Stripe API", "REST API"],
        keyFeatures: [
            "Dynamic product catalog with 40+ items fetched from live API",
            "Firebase Authentication with persistent login state",
            "Responsive UI with grid/list views and animated transitions",
            "Shopping cart with real-time total and session persistence",
            "Secure Stripe payment integration with test/live modes",
            "Detailed product pages with specs, pricing, and image galleries",
            "Global state management using VxState for performance",
            "Offline caching and custom themes with light/dark mode support",
        ],
        githubUrl: "https://github.com/Waqiur/GadgetHive",
        category: "Mobile Application Development",
    },
];

// Programming languages
export const programmingSkills = [
    {
        name: "Java",
        icon: "SiJava",
        color: "from-red-500 to-red-600",
        textColor: "text-red-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "JavaScript",
        icon: "SiJavascript",
        color: "from-yellow-400 to-yellow-500",
        textColor: "text-yellow-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "TypeScript",
        icon: "SiTypescript",
        color: "from-blue-500 to-blue-600",
        textColor: "text-blue-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "HTML",
        icon: "SiHtml5",
        color: "from-orange-500 to-orange-600",
        textColor: "text-orange-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "CSS",
        icon: "SiCss3",
        color: "from-blue-500 to-blue-600",
        textColor: "text-blue-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "SQL",
        icon: "SiPostgresql",
        color: "from-blue-400 to-blue-500",
        textColor: "text-blue-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "C#",
        icon: "SiCsharp",
        color: "from-purple-500 to-purple-600",
        textColor: "text-purple-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "Dart",
        icon: "SiDart",
        color: "from-blue-400 to-blue-500",
        textColor: "text-blue-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "Python",
        icon: "SiPython",
        color: "from-blue-500 to-yellow-500",
        textColor: "text-blue-500",
        bgColor: "bg-slate-800",
    },
];

// Frameworks & Libraries
export const frameworkSkills = [
    {
        name: "React",
        icon: "SiReact",
        color: "from-cyan-400 to-cyan-500",
        textColor: "text-cyan-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "Next.js",
        icon: "SiNextdotjs",
        color: "from-gray-300 to-gray-400",
        textColor: "text-gray-300",
        bgColor: "bg-slate-800",
    },
    {
        name: "Node.js",
        icon: "SiNodedotjs",
        color: "from-green-500 to-green-600",
        textColor: "text-green-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "Express.js",
        icon: "SiExpress",
        color: "from-gray-400 to-gray-500",
        textColor: "text-gray-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "Flutter",
        icon: "SiFlutter",
        color: "from-blue-400 to-blue-500",
        textColor: "text-blue-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "Tailwind CSS",
        icon: "SiTailwindcss",
        color: "from-cyan-400 to-cyan-500",
        textColor: "text-cyan-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "Bootstrap",
        icon: "SiBootstrap",
        color: "from-purple-500 to-purple-600",
        textColor: "text-purple-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "MongoDB",
        icon: "SiMongodb",
        color: "from-green-500 to-green-600",
        textColor: "text-green-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "Firebase",
        icon: "SiFirebase",
        color: "from-yellow-500 to-orange-500",
        textColor: "text-yellow-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "Supabase",
        icon: "SiSupabase",
        color: "from-green-500 to-green-600",
        textColor: "text-green-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "ASP.NET",
        icon: "SiDotnet",
        color: "from-purple-500 to-purple-600",
        textColor: "text-purple-500",
        bgColor: "bg-slate-800",
    },
];

// Tools & technologies
export const toolSkills = [
    {
        name: "VS Code",
        icon: "SiVisualstudiocode",
        color: "from-blue-500 to-blue-600",
        textColor: "text-blue-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "Android Studio",
        icon: "SiAndroidstudio",
        color: "from-green-500 to-green-600",
        textColor: "text-green-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "IntelliJ IDEA",
        icon: "SiIntellijidea",
        color: "from-pink-500 to-pink-600",
        textColor: "text-pink-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "PyCharm",
        icon: "SiPycharm",
        color: "from-green-400 to-green-500",
        textColor: "text-green-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "SQL Server",
        icon: "SiMicrosoftsqlserver",
        color: "from-red-500 to-red-600",
        textColor: "text-red-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "Git",
        icon: "SiGit",
        color: "from-orange-500 to-orange-600",
        textColor: "text-orange-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "GitHub",
        icon: "SiGithub",
        color: "from-gray-400 to-gray-500",
        textColor: "text-gray-400",
        bgColor: "bg-slate-800",
    },
    {
        name: "Linux",
        icon: "SiLinux",
        color: "from-yellow-500 to-yellow-600",
        textColor: "text-yellow-500",
        bgColor: "bg-slate-800",
    },
    {
        name: "Postman",
        icon: "SiPostman",
        color: "from-orange-500 to-orange-600",
        textColor: "text-orange-500",
        bgColor: "bg-slate-800",
    },
];
